### ISSUE TITLE
[1.3][benchmark] Small size object benchmark

### ISSUE THREAD

**Issue by yosukehara** [leo-project/notes#18]
## Environment and Configuration
- OS: Ubuntu Server 14.04.3
- Erlang/OTP: 17.5
- LeoFS: 1.3.0
- CPU: Intel Xeon E5-2630 v3 @ 2.40GHz
- LeoFS' system
  - # of leo_gateway: 1
  - # of leo_storage: 5
  - # of leo_manager: 2
## Report
- https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.0/front/20161006_image_f20m_rw_1

**Comment by yosukehara** [comment]
Everyone cannot understand the detail of the benchmark report. We need to add some items in the benchmark report as below:

```markdown
### Summary
- Description

### Finding issues
- Subject
   - What happened and How to reproduce if possible
   - Information
       - `leofs-doctor` result
       - Summary of errors
           - Description
           - Error log files
       - [Status:[open|close]] [A link of LeoFS' issue]

### Next Action
- Subject
    - Description
```

**Comment by windkit** [comment]
## [PUT] Node overload, [GET] Stable around 600MB/s
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.0/front/20161006_image_f20m_rw_1

### LeoFS Settings
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: 20,000,000 x (4KB~128KB, avg. 32KB)
 - [PUT] Partitioned Sequential
 - [GET] Random

### Summary
 - During Loading Phase, the throughput is decreasing over time
   - Max: 600MB/s, Min: 100MB/s
   - Occasional troughs
   - Disk Write are buffered at the beginning
   - When a Storage Node is overloaded, requests are rejected/timeout
   - Object Repair further stresses nodes with background object read/write

### Next Action
- Collect Error Log during Loading Phase
- Test with Watchdog

**Comment by windkit** [comment]
## [Watchdog] Load Slow down, Read Similar
[Result with Watchdog] (https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161018_image_f10m_rw_watchdog_1)
[Result without Watchdog] (https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161018_image_f10m_rw_1)

### Methodology
 - Data Set: 10,000,000 x (4KB~128KB, avg. 32KB)
 - Turn on Disk Watchdog
   - Check Interval: 1 sec
   - R/W Bandwidth: 400MB/s
   - Disk Utilization: 90%

### Result
 - Loading time for 10,000,000 objects increased from 940s to 1150s (+22%)
 - Number of errors during write increased from 39 to 333 (9x)
 - Read shows very similar result

### Logs
[Loading result with/without watchdog] (https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161018_image_f10m_load_watchdog_1)
 - Has a closer look in the logs 
 - With watchdog, Gateway received more timeout errors with `leo_storage_handler_object:put`
 - With watchdog, Gateway received bunch of "Replicate failure" with `leo_storage_handler_object:put`
 - With watchdog, Storage sometimes failed to fix the consistency
