### ISSUE TITLE
[1.3][benchmark] Checking the impact on performance when a node is killed

### ISSUE THREAD

**Issue by yosukehara** [leo-project/notes#19]
## Environment and Configuration
- OS: Ubuntu Server 14.04.3
- Erlang/OTP: 17.5
- LeoFS: 1.3.0
- CPU: Intel Xeon E5-2630 v3 @ 2.40GHz
- LeoFS' system
  - number of leo_gateway: 1
  - number of leo_storage: 5
  - number of leo_manager: 2
## Report
- https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.0/front/20161007_image_f4m_rw_nodekill_1

**Comment by yosukehara** [comment]
Everyone cannot understand the detail of the benchmark report. We need to add some items in the benchmark report as below:

```markdown
### Summary
- Description

### Finding issues
- Subject
   - What happened and How to reproduce if possible
   - Information
       - `leofs-doctor` result
       - Summary of errors
           - Description
           - Error log files
       - [Status:[open|close]] [A link of LeoFS' issue]

### Next Action
- Subject
    - Description
```

**Comment by windkit** [comment]
## [PUT] Node Overload, [GET] Stable
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.0/front/20161007_image_f4m_rw_nodekill_1

### LeoFS Settings
 - 1 gateway, 5 storage, 10Gbps Link
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: 4,000,000 x (4KB~128KB, avg. 32KB)
 - Node Kill during Load/Read
 - [PUT] Partitioned Sequential
 - [GET] Random

### Summary
- Loading Results with and without node being kiiled are similar
- During read, the received throughput from client is stable
    - Before the first node is killed, the effective data set is small enough to sit in memory (page cache)
    - After nodes are killed, nodes are receiving more requests

### Next Action
- Similar to base image case https://github.com/leo-project/notes/issues/18, need a closer look on loading phase
