### ISSUE TITLE
[1.3][benchmark] Check Random Access Performance in LeoFS

### ISSUE THREAD

**Issue by windkit** [leo-project/notes#22]
## Description
We want to check the performance of random access within objects in LeoFS, we will conduct it in two steps.
1. Load Objects into LeoFS (Small/Large)
2. Randomly read portion of random object

## Environment and Configuration
- OS: Ubuntu Server 14.04.3
- Erlang/OTP: 17.5
- LeoFS: 1.3.0
- CPU: Intel Xeon E5-2630 v3 @ 2.40GHz
- LeoFS' system
  - number of leo_gateway: 1
  - number of leo_storage: 5
  - number of leo_manager: 2

**Comment by windkit** [comment]
## Random Read 100KB from 1MB Objects (Latency <20ms)
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161116_fix1m_f300k_range_100k_1

### LeoFS Settings
 - 1 gateway, 5 storage, 10Gbps Link
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: 300,000 x 1MB
 - Random Offset, Random Key
 - [GET] Random

### Summary
Delivered Consistent Bandwidth around 600MB/s, similar result to whole object read
![summary](https://cloud.githubusercontent.com/assets/360884/20472968/e5f613e0-b000-11e6-8ee7-9bbec74869f5.png)

**Comment by windkit** [comment]
## Random Read 100KB from 50MB Objects (95 percentile Latency >200ms)
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161116_fix1m_f300k_range_100k_1

### LeoFS Settings
 - 1 gateway, 5 storage, 10Gbps Link
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: 6,000 x 50MB
 - Random Offset, Random Key
 - [GET] Random

### Summary
Delivered Consistent Bandwidth around 400MB/s, lower than (100KB) in small Object (1MB). We may have to check if there is bottleneck when reading from chunked objects.
![summary 1](https://cloud.githubusercontent.com/assets/360884/20473015/2e4d1a62-b001-11e6-9910-d9286544edbd.png)

**Comment by windkit** [comment]
## Random Read 200KB from 1MB Objects
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161117_fix50m_f6k_range_100k_1

### LeoFS Settings
 - 1 gateway, 5 storage, 10Gbps Link
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: Data Set: 300,000 x 1MB
 - Random Offset, Random Key
 - [GET] Random

### Summary
![summary 2](https://cloud.githubusercontent.com/assets/360884/20506934/e3aa89c8-b09a-11e6-9597-87adb0178234.png)

**Comment by windkit** [comment]
## Random Read 200KB Objects
https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/front/20161122_fix200m_f1.5m_read_1

### LeoFS Settings
 - 1 gateway, 5 storage, 10Gbps Link
 - No GW Cache
 - SSD-backed Storage

### Methodology
 - Basho Bench leofs driver
 - 64 processes in erlang performing HTTP PUT/GET
 - Data Set: Data Set: 1500,000 x 200KB
 - Random Offset, Random Key
 - [GET] Random

### Summary
![summary 3](https://cloud.githubusercontent.com/assets/360884/20508137/c7d4bb94-b0a2-11e6-8d32-0c5cd130dc64.png)

**Comment by PatelParas** [comment]
which filesystem mount do we use for this benchmarking ? and do we enable barriers option for mount ?

**Comment by windkit** [comment]
@PatelParas The test is done with S3 API Client, which do you refer to?
